@LAZYGLOBAL OFF.
RUNPATH("0:/cz10b/config.ks").
RUNPATH("0:/cz10b/controller.ks").

CLEARSCREEN.
PRINT "CZ-10B kOS powered-descent acceptance".
PRINT "Waiting for the test suspension release...".

// While attached, the processor and recovery platform belong to one vessel.
// The C# harness only releases the stage and changes the active vessel; all
// subsequent flight-control outputs originate in this KerboScript program.
WAIT UNTIL SHIP:PARTSNAMED("CZ10B-RecoveryPlatform"):LENGTH = 0.
// The observer assigns the platform as KSP's target immediately after making
// this stage active.  This avoids a kOS 1.6 LIST VESSELS exception during the
// vessel-index rebuild following decoupling; it does not supply control input.
WAIT UNTIL HASTARGET.
LOCAL RECOVERY_SHIP IS TARGET.
LOCAL MISSION_ID IS ROUND(TIME:SECONDS,0).
LOG "mission,phase,ut,altitude,hook_height,v_vertical,v_horizontal,h_error,throttle,tilt,mass,max_thrust"
    TO "0:/cz10b/hover-telemetry.csv".

SAS OFF.
RCS OFF.
BRAKES OFF.
LOCAL ENGINES IS LIST().
LIST ENGINES IN ENGINES.
FOR ENGINE IN ENGINES { ENGINE:ACTIVATE. }
WAIT UNTIL SHIP:AVAILABLETHRUST > 0.

LOCAL VERTICAL_INTEGRAL IS 0.
LOCAL PREVIOUS_TIME IS TIME:SECONDS.
LOCAL LAST_LOG IS TIME:SECONDS - TELEMETRY_PERIOD.
LOCAL START_TIME IS TIME:SECONDS.
LOCK STEERING TO UP.
LOCK THROTTLE TO 0.

UNTIL HOOK_CAPTURED() OR TIME:SECONDS - START_TIME > 75 {
    LOCAL NOW IS TIME:SECONDS.
    LOCAL DT IS CLAMP(NOW - PREVIOUS_TIME, 0.001, 0.1).
    SET PREVIOUS_TIME TO NOW.

    LOCAL UP_VEC IS SHIP:UP:VECTOR:NORMALIZED.
    LOCAL REL_POS IS NET_POSITION(RECOVERY_SHIP) - SHIP:POSITION.
    LOCAL HEIGHT IS -VDOT(REL_POS, UP_VEC).
    LOCAL HOOK_HEIGHT IS HEIGHT + HOOK_ABOVE_COM.
    LOCAL HORIZONTAL_POS IS VXCL(UP_VEC, REL_POS).
    LOCAL REL_VEL IS SHIP:VELOCITY:SURFACE - RECOVERY_SHIP:VELOCITY:SURFACE.
    LOCAL VERTICAL_V IS VDOT(REL_VEL, UP_VEC).
    LOCAL HORIZONTAL_VEL IS VXCL(UP_VEC, REL_VEL).

    LOCAL G_ACC IS SHIP:BODY:MU / ((SHIP:BODY:RADIUS + SHIP:ALTITUDE)^2).
    LOCAL AVAILABLE_ACC IS SHIP:AVAILABLETHRUST / MAX(SHIP:MASS, 0.001).
    LOCAL ALT_BLEND IS CLAMP(HOOK_HEIGHT / 80, 0, 1).
    LOCAL H_POS_KP IS H_POS_KP_HIGH * ALT_BLEND + H_POS_KP_LOW * (1 - ALT_BLEND).
    LOCAL DESIRED_H_VEL IS CLAMPV(HORIZONTAL_POS * H_POS_KP, 8).
    LOCAL H_ACCEL IS CLAMPV((DESIRED_H_VEL - HORIZONTAL_VEL) * H_VEL_KP, 8).

    LOCAL DESIRED_V IS -CLAMP(0.42 * SQRT(2 * G_ACC * MAX(HOOK_HEIGHT, 0.2)),
                              CAPTURE_FINAL_SPEED, 12).
    IF HOOK_HEIGHT < 35 { SET DESIRED_V TO -CLAMP(HOOK_HEIGHT * 0.13, CAPTURE_FINAL_SPEED, 4). }
    IF HOOK_HEIGHT < 5 { SET DESIRED_V TO -CAPTURE_FINAL_SPEED. }

    SET VERTICAL_INTEGRAL TO CLAMP(VERTICAL_INTEGRAL + (DESIRED_V - VERTICAL_V) * DT,
                                   -15, 15).
    LOCAL VERTICAL_ACCEL_CMD IS G_ACC + V_VEL_KP * (DESIRED_V - VERTICAL_V)
                                + V_VEL_KI * VERTICAL_INTEGRAL.
    SET VERTICAL_ACCEL_CMD TO CLAMP(VERTICAL_ACCEL_CMD, 0, AVAILABLE_ACC * 0.96).
    LOCAL THROTTLE_CMD IS CLAMP(SHIP:MASS * VERTICAL_ACCEL_CMD /
                                MAX(SHIP:AVAILABLETHRUST, 0.001), 0, 1).

    LOCAL TILT_LIMIT IS LANDING_MAX_TILT.
    LOCAL MAX_H_ACCEL IS MAX(VERTICAL_ACCEL_CMD, G_ACC) * TAN(TILT_LIMIT).
    SET H_ACCEL TO CLAMPV(H_ACCEL, MAX_H_ACCEL).
    LOCAL DESIRED_THRUST IS UP_VEC * MAX(VERTICAL_ACCEL_CMD, G_ACC * 0.2) + H_ACCEL.
    LOCAL TILT_CMD IS VANG(DESIRED_THRUST, UP_VEC).

    LOCK STEERING TO LOOKDIRUP(DESIRED_THRUST, SHIP:FACING:TOPVECTOR).
    LOCK THROTTLE TO THROTTLE_CMD.

    IF NOW - LAST_LOG >= TELEMETRY_PERIOD {
        LOCAL ROW IS MISSION_ID + ",HOVER_TEST," + ROUND(NOW,3)
            + "," + ROUND(SHIP:ALTITUDE,2) + "," + ROUND(HOOK_HEIGHT,2)
            + "," + ROUND(VERTICAL_V,3) + "," + ROUND(HORIZONTAL_VEL:MAG,3)
            + "," + ROUND(HORIZONTAL_POS:MAG,3) + "," + ROUND(THROTTLE_CMD,4)
            + "," + ROUND(TILT_CMD,3) + "," + ROUND(SHIP:MASS,3)
            + "," + ROUND(SHIP:AVAILABLETHRUST,2).
        LOG ROW TO "0:/cz10b/hover-telemetry.csv".
        SET LAST_LOG TO NOW.
    }

    PRINT "hook height " + ROUND(HOOK_HEIGHT,2) + " m    " AT(0,5).
    PRINT "vertical    " + ROUND(VERTICAL_V,2) + " m/s  " AT(0,6).
    PRINT "cross error " + ROUND(HORIZONTAL_POS:MAG,2) + " m    " AT(0,7).
    PRINT "throttle    " + ROUND(THROTTLE_CMD,3) + "      " AT(0,8).
    WAIT 0.02.
}

LOCK THROTTLE TO 0.
LOCK STEERING TO UP.
IF HOOK_CAPTURED() {
    PRINT "CAPTURE COMPLETE" AT(0,10).
    LOG MISSION_ID + ",CAPTURE," + ROUND(TIME:SECONDS,3)
        TO "0:/cz10b/hover-telemetry.csv".
} ELSE {
    PRINT "TEST TIMEOUT" AT(0,10).
    LOG MISSION_ID + ",TIMEOUT," + ROUND(TIME:SECONDS,3)
        TO "0:/cz10b/hover-telemetry.csv".
}
WAIT UNTIL FALSE.
