@LAZYGLOBAL OFF.
RUNPATH("0:/cz10b/config.ks").
RUNPATH("0:/cz10b/controller.ks").

CLEARSCREEN.
PRINT "CZ-10B cable-net recovery demonstrator".
PRINT "Searching for vessel: " + TARGET_VESSEL_NAME.

LOCAL RECOVERY_SHIP IS 0.
LOCAL COUNTDOWN_SECONDS IS 5.
IF SHIP:PARTSNAMED("CZ10B-RecoveryPlatform"):LENGTH > 0 {
    PRINT "Waiting for integrated mission rail release.".
    WAIT UNTIL SHIP:PARTSNAMED("CZ10B-RecoveryPlatform"):LENGTH = 0.
    WAIT UNTIL HASTARGET.
    SET RECOVERY_SHIP TO TARGET.
    SET COUNTDOWN_SECONDS TO 0.
} ELSE {
    SET RECOVERY_SHIP TO FIND_RECOVERY_SHIP(TARGET_VESSEL_NAME).
}
IF RECOVERY_SHIP = 0 {
    PRINT "ERROR: Recovery Ship not found.".
    PRINT "Launch and park the ship first; keep its exact vessel name.".
    WAIT 10.
    SHUTDOWN.
}

SET TARGET TO RECOVERY_SHIP.
LOCAL MISSION_ID IS ROUND(TIME:SECONDS,0).
LOG "mission,phase,ut,altitude,hook_height,v_vertical,v_horizontal,h_error,throttle,tilt,mass,max_thrust"
    TO "0:/cz10b/telemetry.csv".

SAS OFF.
RCS ON.
BRAKES OFF.

PRINT "Target locked: " + RECOVERY_SHIP:NAME.
PRINT "Booster probe core must be the craft root.".
FROM { LOCAL COUNTDOWN IS COUNTDOWN_SECONDS. } UNTIL COUNTDOWN = 0 STEP { SET COUNTDOWN TO COUNTDOWN - 1. } DO {
    PRINT "T-" + COUNTDOWN AT(0,8).
    WAIT 1.
}

// The first staging event ignites the booster. Keep upper-stage ignition and
// the interstage decoupler in the later separation stage.
LOCK STEERING TO UP.
LOCK THROTTLE TO 1.
LOCAL MISSION_ENGINES IS SHIP:ENGINES.
FOR ENGINE IN MISSION_ENGINES {
    IF ENGINE:NAME = "CZ10B-DemoBooster" { ENGINE:ACTIVATE. }
}
PRINT "LIFTOFF" AT(0,10).

LOCAL LAST_LOG IS TIME:SECONDS.
UNTIL SHIP:ALTITUDE > SEPARATION_ALTITUDE {
    LOCAL FRACTION IS CLAMP(SHIP:ALTITUDE / SEPARATION_ALTITUDE, 0, 1).
    LOCAL PITCH_CMD IS 90 - 52 * FRACTION.
    IF SHIP:GROUNDSPEED > ASCENT_MAX_SPEED {
        LOCK THROTTLE TO 0.45.
    } ELSE {
        LOCK THROTTLE TO 1.
    }
    LOCAL ASCENT_UP IS SHIP:UP:VECTOR:NORMALIZED.
    LOCAL ASCENT_TARGET_OFFSET IS VXCL(ASCENT_UP,
        NET_POSITION(RECOVERY_SHIP) - SHIP:POSITION).
    IF ASCENT_TARGET_OFFSET:MAG > 1 {
        LOCAL ASCENT_DIRECTION IS ASCENT_UP * SIN(PITCH_CMD)
            + ASCENT_TARGET_OFFSET:NORMALIZED * COS(PITCH_CMD).
        LOCK STEERING TO LOOKDIRUP(ASCENT_DIRECTION, SHIP:FACING:TOPVECTOR).
    } ELSE {
        LOCK STEERING TO UP.
    }

    IF TIME:SECONDS - LAST_LOG >= TELEMETRY_PERIOD {
        WRITE_TELEMETRY("ASCENT", MISSION_ID, SHIP:ALTITUDE, 0,
            SHIP:VERTICALSPEED, SHIP:GROUNDSPEED, RECOVERY_SHIP:GEOPOSITION:DISTANCE,
            THROTTLE, 90 - PITCH_CMD).
        SET LAST_LOG TO TIME:SECONDS.
    }
    WAIT 0.02.
}

LOCK THROTTLE TO 0.
LOCK STEERING TO UP.
WAIT 1.
// Direct part operations remain reliable after the integrated test rail has
// been programmatically released, while KSP's UI staging icon list may not.
FOR ENGINE IN MISSION_ENGINES {
    IF ENGINE:NAME = "CZ10B-DemoUpperStage" { ENGINE:ACTIVATE. }
}
LOCK THROTTLE TO 1.
WAIT 0.2.
LOCAL INTERSTAGES IS SHIP:PARTSNAMED("Decoupler.2").
IF INTERSTAGES:LENGTH = 0 {
    PRINT "ERROR: interstage not found".
    SHUTDOWN.
}
LOCAL DECOUPLE_MODULE IS INTERSTAGES[0]:GETMODULE("ModuleDecouple").
LOCAL DECOUPLE_EVENTS IS DECOUPLE_MODULE:ALLEVENTNAMES.
IF DECOUPLE_EVENTS:LENGTH = 0 {
    PRINT "ERROR: interstage event unavailable".
    SHUTDOWN.
}
DECOUPLE_MODULE:DOEVENT(DECOUPLE_EVENTS[0]).
WAIT 0.2.
LOCK THROTTLE TO 0.
PRINT "STAGE SEPARATION - BOOSTER GUIDANCE ACTIVE" AT(0,11).
WAIT 1.
BRAKES ON. // four stock airbrakes serve as the grid-fin analogue

// Closed-loop powered return. Positions and surface velocities are evaluated
// in the same SHIP-RAW frame, so this also tracks a slowly moving recovery ship.
LOCAL VERTICAL_INTEGRAL IS 0.
LOCAL PREVIOUS_TIME IS TIME:SECONDS.
LOCAL WAS_CENTERING IS FALSE.
SET LAST_LOG TO TIME:SECONDS.

UNTIL HOOK_CAPTURED() {
    LOCAL NOW IS TIME:SECONDS.
    LOCAL DT IS CLAMP(NOW - PREVIOUS_TIME, 0.001, 0.1).
    SET PREVIOUS_TIME TO NOW.

    LOCAL UP_VEC IS SHIP:UP:VECTOR:NORMALIZED.
    LOCAL REL_POS IS NET_POSITION(RECOVERY_SHIP) - SHIP:POSITION.
    LOCAL HEIGHT IS -VDOT(REL_POS, UP_VEC).
    LOCAL HOOK_HEIGHT IS HEIGHT + HOOK_ABOVE_COM.
    LOCAL HORIZONTAL_POS IS VXCL(UP_VEC, REL_POS).

    LOCAL REL_VEL IS SHIP:VELOCITY:SURFACE - RECOVERY_SHIP:VELOCITY:SURFACE.
    LOCAL VERTICAL_V IS VDOT(REL_VEL, UP_VEC).
    LOCAL HORIZONTAL_VEL IS VXCL(UP_VEC, REL_VEL).

    LOCAL G_ACC IS SHIP:BODY:MU / ((SHIP:BODY:RADIUS + SHIP:ALTITUDE)^2).
    LOCAL AVAILABLE_ACC IS SHIP:AVAILABLETHRUST / MAX(SHIP:MASS, 0.001).
    LOCAL MAX_NET_ACCEL IS MAX(AVAILABLE_ACC - G_ACC, 0.1).
    LOCAL STOP_DISTANCE IS 0.
    IF VERTICAL_V < 0 {
        SET STOP_DISTANCE TO (VERTICAL_V^2) / (2 * MAX_NET_ACCEL) * STOP_DISTANCE_SAFETY.
    }

    // Position loop produces a desired horizontal velocity; velocity loop then
    // produces lateral acceleration. Limits tighten close to the net.
    LOCAL ALT_BLEND IS CLAMP(HOOK_HEIGHT / 800, 0, 1).
    LOCAL H_SPEED_LIMIT IS 8 + (MAX_HORIZONTAL_SPEED - 8) * ALT_BLEND.
    IF HOOK_HEIGHT < CENTERING_HOLD_ALTITUDE {
        SET H_SPEED_LIMIT TO TERMINAL_HORIZONTAL_SPEED.
    }
    LOCAL H_POS_KP IS H_POS_KP_HIGH * ALT_BLEND + H_POS_KP_LOW * (1 - ALT_BLEND).
    LOCAL DESIRED_H_VEL IS CLAMPV(HORIZONTAL_POS * H_POS_KP,
                                  H_SPEED_LIMIT).
    LOCAL H_ACCEL IS CLAMPV((DESIRED_H_VEL - HORIZONTAL_VEL) * H_VEL_KP, 15).

    LOCAL DESIRED_V IS -CLAMP(0.42 * SQRT(2 * G_ACC * MAX(HOOK_HEIGHT, 0.2)),
                              CAPTURE_FINAL_SPEED, 70).
    IF HOOK_HEIGHT < 35 { SET DESIRED_V TO -CLAMP(HOOK_HEIGHT * 0.13, CAPTURE_FINAL_SPEED, 4). }
    IF HOOK_HEIGHT < 5 { SET DESIRED_V TO -CAPTURE_FINAL_SPEED. }
    LOCAL CENTERING_REQUIRED IS HOOK_HEIGHT < CENTERING_HOLD_ALTITUDE
        AND HORIZONTAL_POS:MAG > 5.
    IF CENTERING_REQUIRED {
        SET DESIRED_V TO 0. // hold above the net until all four hooks fit
    }
    IF WAS_CENTERING AND NOT CENTERING_REQUIRED {
        SET VERTICAL_INTEGRAL TO 0. // avoid hover-mode windup delaying final descent
    }
    SET WAS_CENTERING TO CENTERING_REQUIRED.

    // Burn laterally only when the velocity loop actually asks for meaningful
    // acceleration. A large position error with velocity already aimed at the
    // ship should remain a ballistic coast, not a gravity-cancelling hover burn.
    LOCAL HORIZONTAL_BURN IS H_ACCEL:MAG > 0.5 AND
        (HORIZONTAL_POS:MAG > 150 OR HORIZONTAL_VEL:MAG > 10 OR HOOK_HEIGHT < 5000).
    LOCAL SHOULD_BURN IS HOOK_HEIGHT <= STOP_DISTANCE + BURN_ALTITUDE_MARGIN
                         OR (HOOK_HEIGHT < 100 AND SHIP:VERTICALSPEED > -2)
                         OR CENTERING_REQUIRED
                         OR HORIZONTAL_BURN.
    LOCAL THROTTLE_CMD IS 0.
    LOCAL VERTICAL_ACCEL_CMD IS 0.
    IF SHOULD_BURN {
        SET VERTICAL_INTEGRAL TO CLAMP(VERTICAL_INTEGRAL + (DESIRED_V - VERTICAL_V) * DT,
                                       -15, 15).
        SET VERTICAL_ACCEL_CMD TO G_ACC + V_VEL_KP * (DESIRED_V - VERTICAL_V)
                                  + V_VEL_KI * VERTICAL_INTEGRAL.
        SET VERTICAL_ACCEL_CMD TO CLAMP(VERTICAL_ACCEL_CMD, 0, AVAILABLE_ACC * 0.96).
    }

    LOCAL TILT_LIMIT IS ENTRY_MAX_TILT * ALT_BLEND + LANDING_MAX_TILT * (1 - ALT_BLEND).
    LOCAL VERTICAL_THRUST_CMD IS VERTICAL_ACCEL_CMD.
    IF HORIZONTAL_BURN AND VERTICAL_THRUST_CMD < G_ACC {
        SET VERTICAL_THRUST_CMD TO G_ACC.
    }
    LOCAL MAX_H_ACCEL IS MAX(VERTICAL_THRUST_CMD, G_ACC * 0.2) * TAN(TILT_LIMIT).
    SET H_ACCEL TO CLAMPV(H_ACCEL, MAX_H_ACCEL).
    LOCAL DESIRED_THRUST IS UP_VEC * MAX(VERTICAL_THRUST_CMD, G_ACC * 0.2) + H_ACCEL.
    LOCAL TILT_CMD IS VANG(DESIRED_THRUST, UP_VEC).
    IF SHOULD_BURN {
        SET THROTTLE_CMD TO CLAMP(SHIP:MASS * DESIRED_THRUST:MAG /
                                  MAX(SHIP:AVAILABLETHRUST, 0.001), 0, 1).
    }

    IF SHOULD_BURN {
        LOCK STEERING TO LOOKDIRUP(DESIRED_THRUST, SHIP:FACING:TOPVECTOR).
        LOCK THROTTLE TO THROTTLE_CMD.
    } ELSE {
        LOCK STEERING TO SRFRETROGRADE.
        LOCK THROTTLE TO 0.
    }

    IF NOW - LAST_LOG >= TELEMETRY_PERIOD {
        WRITE_TELEMETRY("RETURN", MISSION_ID, SHIP:ALTITUDE, HOOK_HEIGHT,
            VERTICAL_V, HORIZONTAL_VEL:MAG, HORIZONTAL_POS:MAG,
            THROTTLE_CMD, TILT_CMD).
        SET LAST_LOG TO NOW.
    }

    PRINT "hook height " + ROUND(HOOK_HEIGHT,1) + " m    " AT(0,13).
    PRINT "vertical    " + ROUND(VERTICAL_V,2) + " m/s  " AT(0,14).
    PRINT "cross error " + ROUND(HORIZONTAL_POS:MAG,1) + " m    " AT(0,15).
    PRINT "throttle    " + ROUND(THROTTLE_CMD,3) + "      " AT(0,16).

    // This guard leaves the booster hanging in the net even if an old kOS build
    // cannot read the custom module field immediately after joint creation.
    IF HOOK_HEIGHT < 0.6 AND ABS(VERTICAL_V) < 1.2 AND HORIZONTAL_POS:MAG < 8 {
        LOCK THROTTLE TO 0.
    }
    IF AG10 {
        PRINT "MANUAL ABORT (AG10)".
        BREAK.
    }
    WAIT 0.02.
}

LOCK THROTTLE TO 0.
LOCK STEERING TO UP.
RCS OFF.
PRINT "CAPTURE COMPLETE" AT(0,18).
LOG MISSION_ID + ",CAPTURE," + ROUND(TIME:SECONDS,3) TO "0:/cz10b/telemetry.csv".
WAIT UNTIL FALSE.
