@LAZYGLOBAL OFF.
RUNPATH("0:/cz10b/config.ks").
RUNPATH("0:/cz10b/controller.ks").

CLEARSCREEN.
PRINT "CZ-10B cable-net recovery demonstrator".
PRINT "Searching for vessel: " + TARGET_VESSEL_NAME.

LOCAL RECOVERY_SHIP IS 0.
LOCAL COUNTDOWN_SECONDS IS 5.
LOCAL AUTOMATED_DEPLOYMENT IS FALSE.
IF SHIP:PARTSNAMED("CZ10B-RecoveryPlatform"):LENGTH > 0 {
    PRINT "Waiting for integrated mission rail release.".
    WAIT UNTIL SHIP:PARTSNAMED("CZ10B-RecoveryPlatform"):LENGTH = 0.
    WAIT UNTIL HASTARGET.
    SET RECOVERY_SHIP TO TARGET.
    SET AUTOMATED_DEPLOYMENT TO TRUE.
} ELSE {
    IF HASTARGET {
        // On a slow first physics frame the observer may have already separated
        // the rail and bound the platform before this boot program starts. Reuse
        // that target instead of enumerating vessels while one is unpacking.
        SET RECOVERY_SHIP TO TARGET.
        SET AUTOMATED_DEPLOYMENT TO TRUE.
    } ELSE {
        SET RECOVERY_SHIP TO FIND_RECOVERY_SHIP(TARGET_VESSEL_NAME).
    }
}
IF AUTOMATED_DEPLOYMENT {
    // The observer separates and deploys the recovery ship first. For a sea
    // run, wait until its great-circle distance proves the move has completed.
    LOCAL DEPLOYMENT_TIMEOUT IS TIME:SECONDS + 6.
    WAIT UNTIL RECOVERY_SHIP:GEOPOSITION:DISTANCE > 1000
        OR TIME:SECONDS >= DEPLOYMENT_TIMEOUT.
    SET COUNTDOWN_SECONDS TO 10.
}
IF RECOVERY_SHIP = 0 {
    PRINT "ERROR: Recovery Ship not found.".
    PRINT "Launch and park the ship first; keep its exact vessel name.".
    WAIT 10.
    SHUTDOWN.
}

SET TARGET TO RECOVERY_SHIP.
LOCAL MISSION_ID IS ROUND(TIME:SECONDS,0).
LOG "mission,phase,ut,altitude,hook_height,v_vertical,v_horizontal,h_error,throttle,tilt,mass,max_thrust"
    TO "0:/cz10b/telemetry.csv".

SAS OFF.
RCS ON.
BRAKES OFF.

PRINT "Target locked: " + RECOVERY_SHIP:NAME.
PRINT "Booster probe core must be the craft root.".
FROM { LOCAL COUNTDOWN IS COUNTDOWN_SECONDS. } UNTIL COUNTDOWN = 0 STEP { SET COUNTDOWN TO COUNTDOWN - 1. } DO {
    PRINT "T-" + COUNTDOWN AT(0,8).
    WAIT 1.
}

// Start the engine while the real TT18-A clamps still carry the vehicle. Release
// only after measured thrust-to-weight exceeds one.
LOCK STEERING TO UP.
LOCK THROTTLE TO 1.
LOCAL ENGINE_LOAD_DEADLINE IS TIME:SECONDS + 15.
WAIT UNTIL SHIP:ENGINES:LENGTH > 0
    OR TIME:SECONDS >= ENGINE_LOAD_DEADLINE.
LOCAL MISSION_ENGINES IS SHIP:ENGINES.
IF MISSION_ENGINES:LENGTH = 0 {
    PRINT "ABORT: engine modules did not load" AT(0,12).
    LOCK THROTTLE TO 0.
    SHUTDOWN.
}
FOR ENGINE IN MISSION_ENGINES {
    IF ENGINE:NAME = "CZ10B-DemoBooster" { ENGINE:ACTIVATE. }
}
PRINT "ENGINE START - TT18-A HOLD" AT(0,10).
LOCAL RELEASE_TWR IS 0.
LOCAL RELEASE_DEADLINE IS TIME:SECONDS + 8.
UNTIL RELEASE_TWR > 1.02 OR TIME:SECONDS >= RELEASE_DEADLINE {
    LOCAL CURRENT_THRUST IS 0.
    FOR ENGINE IN MISSION_ENGINES {
        IF ENGINE:NAME = "CZ10B-DemoBooster" {
            // Activation is idempotent and closes a slow-unpack race in which
            // the first request can arrive before the engine finishes starting.
            ENGINE:ACTIVATE.
            SET CURRENT_THRUST TO CURRENT_THRUST + ENGINE:THRUST.
        }
    }
    LOCAL PAD_G IS SHIP:BODY:MU / ((SHIP:BODY:RADIUS + SHIP:ALTITUDE)^2).
    SET RELEASE_TWR TO CURRENT_THRUST / MAX(SHIP:MASS * PAD_G, 0.001).
    PRINT "hold-down TWR " + ROUND(RELEASE_TWR,2) + "   " AT(0,11).
    WAIT 0.05.
}
IF RELEASE_TWR <= 1.02 {
    PRINT "ABORT: TWR did not exceed 1" AT(0,12).
    LOCK THROTTLE TO 0.
    SHUTDOWN.
}
LOCAL RELEASED_CLAMPS IS RELEASE_LAUNCH_CLAMPS().
PRINT "LIFTOFF - released " + RELEASED_CLAMPS + " TT18-A" AT(0,10).
LOG MISSION_ID + ",CLAMP_RELEASE," + ROUND(TIME:SECONDS,3)
    + ",count=" + RELEASED_CLAMPS + ",twr=" + ROUND(RELEASE_TWR,3)
    TO "0:/cz10b/telemetry.csv".

LOCAL LAST_LOG IS TIME:SECONDS.
UNTIL SHIP:ALTITUDE > SEPARATION_ALTITUDE {
    LOCAL TURN_FRACTION IS CLAMP((SHIP:ALTITUDE - ASCENT_TURN_START)
        / (ASCENT_TURN_END - ASCENT_TURN_START), 0, 1).
    // Smoothstep avoids a pitch-rate discontinuity at either end of the turn.
    LOCAL TURN_BLEND IS TURN_FRACTION^2 * (3 - 2 * TURN_FRACTION).
    LOCAL PITCH_CMD IS 90 - ASCENT_TURN_DEGREES * TURN_BLEND.
    IF SHIP:GROUNDSPEED > ASCENT_MAX_SPEED {
        LOCK THROTTLE TO 0.45.
    } ELSE {
        LOCK THROTTLE TO 1.
    }
    LOCK STEERING TO HEADING(ASCENT_HEADING, PITCH_CMD).

    IF TIME:SECONDS - LAST_LOG >= TELEMETRY_PERIOD {
        WRITE_TELEMETRY("ASCENT", MISSION_ID, SHIP:ALTITUDE, 0,
            SHIP:VERTICALSPEED, SHIP:GROUNDSPEED, RECOVERY_SHIP:GEOPOSITION:DISTANCE,
            THROTTLE, 90 - PITCH_CMD).
        SET LAST_LOG TO TIME:SECONDS.
    }
    WAIT 0.02.
}

LOCK THROTTLE TO 0.
LOCAL SEPARATION_ATTITUDE IS SHIP:FACING.
LOCK STEERING TO SEPARATION_ATTITUDE.
WAIT 0.5.
// Direct part operations remain reliable after the integrated test rail has
// been programmatically released, while KSP's UI staging icon list may not.
FOR ENGINE IN MISSION_ENGINES {
    IF ENGINE:NAME = "CZ10B-DemoUpperStage" { ENGINE:ACTIVATE. }
}
LOCK THROTTLE TO 1.
WAIT 0.2.
LOCAL INTERSTAGES IS SHIP:PARTSNAMED("Decoupler.2").
IF INTERSTAGES:LENGTH = 0 {
    PRINT "ERROR: interstage not found".
    SHUTDOWN.
}
LOCAL DECOUPLE_MODULE IS INTERSTAGES[0]:GETMODULE("ModuleDecouple").
LOCAL DECOUPLE_EVENTS IS DECOUPLE_MODULE:ALLEVENTNAMES.
IF DECOUPLE_EVENTS:LENGTH = 0 {
    PRINT "ERROR: interstage event unavailable".
    SHUTDOWN.
}
DECOUPLE_MODULE:DOEVENT(DECOUPLE_EVENTS[0]).
WAIT 0.2.
LOCK THROTTLE TO 0.
PRINT "STAGE SEPARATION - BOOSTER GUIDANCE ACTIVE" AT(0,11).
BRAKES ON. // four stock airbrakes serve as the grid-fin analogue

// 1) Ballistic coast. Hold the separation attitude inertially through apogee.
// Surface prograde rotates extremely quickly when vertical speed crosses zero;
// chasing it made the long empty stage oscillate even with zero throttle.
PRINT "INERTIAL COAST THROUGH APOGEE" AT(0,11).
LOCK THROTTLE TO 0.
LOCAL COAST_ATTITUDE IS SHIP:FACING.
LOCK STEERING TO COAST_ATTITUDE.
SET LAST_LOG TO TIME:SECONDS.
UNTIL SHIP:VERTICALSPEED <= COAST_TRACK_DESCENT_SPEED {
    IF TIME:SECONDS - LAST_LOG >= TELEMETRY_PERIOD {
        WRITE_TELEMETRY("COAST", MISSION_ID, SHIP:ALTITUDE, 0,
            SHIP:VERTICALSPEED, SHIP:GROUNDSPEED,
            RECOVERY_SHIP:GEOPOSITION:DISTANCE, 0, 0).
        SET LAST_LOG TO TIME:SECONDS.
    }
    WAIT 0.02.
}

// 2) Only after a definite descent rate exists, slew smoothly to retrograde.
// The command itself is rate-shaped, instead of handing a discontinuously
// rotating suffix directly to the steering manager.
PRINT "CONTROLLED POST-APOGEE FLIP" AT(0,11).
LOCAL FLIP_START_TIME IS TIME:SECONDS.
LOCAL FLIP_START_VECTOR IS SHIP:FACING:FOREVECTOR:NORMALIZED.
UNTIL TIME:SECONDS - FLIP_START_TIME >= POST_APOGEE_FLIP_SECONDS {
    LOCAL FLIP_BLEND_RAW IS CLAMP((TIME:SECONDS - FLIP_START_TIME)
        / POST_APOGEE_FLIP_SECONDS, 0, 1).
    LOCAL FLIP_BLEND IS FLIP_BLEND_RAW^2 * (3 - 2 * FLIP_BLEND_RAW).
    LOCAL FLIP_TARGET IS (-SHIP:VELOCITY:SURFACE):NORMALIZED.
    LOCAL FLIP_COMMAND IS (FLIP_START_VECTOR * (1 - FLIP_BLEND)
        + FLIP_TARGET * FLIP_BLEND):NORMALIZED.
    LOCK STEERING TO LOOKDIRUP(FLIP_COMMAND, SHIP:UP:VECTOR).
    WAIT 0.05.
}
LOCK STEERING TO SRFRETROGRADE.

PRINT "SINGLE BOOST-BACK BURN" AT(0,11).
LOCAL RETURN_BURN_START IS TIME:SECONDS.
LOCAL RETURN_BURN_DONE IS FALSE.
LOCAL RB_FILTERED_H_ACCEL IS V(0,0,0).
LOCAL RB_INITIAL_UP IS SHIP:UP:VECTOR:NORMALIZED.
LOCAL RB_INITIAL_REL_VEL IS SHIP:VELOCITY:SURFACE
    - RECOVERY_SHIP:VELOCITY:SURFACE.
LOCAL RB_BRAKE_DIRECTION IS (-VXCL(RB_INITIAL_UP,
    RB_INITIAL_REL_VEL)):NORMALIZED.
UNTIL RETURN_BURN_DONE {
    LOCAL RB_UP IS SHIP:UP:VECTOR:NORMALIZED.
    LOCAL RB_REL_POS IS NET_POSITION(RECOVERY_SHIP) - SHIP:POSITION.
    LOCAL RB_H_POS IS VXCL(RB_UP, RB_REL_POS).
    LOCAL RB_REL_VEL IS SHIP:VELOCITY:SURFACE - RECOVERY_SHIP:VELOCITY:SURFACE.
    LOCAL RB_H_VEL IS VXCL(RB_UP, RB_REL_VEL).
    LOCAL RB_DIRECTION IS RB_H_POS:NORMALIZED.
    LOCAL RB_VERTICAL_V IS VDOT(RB_REL_VEL, RB_UP).
    LOCAL RB_G IS SHIP:BODY:MU / ((SHIP:BODY:RADIUS + SHIP:ALTITUDE)^2).
    LOCAL RB_TGO IS COAST_TIME_TO_HEIGHT(SHIP:ALTITUDE, RB_VERTICAL_V,
        TERMINAL_START_ALTITUDE, RB_G).
    // Shape the horizontal state for a direct terminal corridor instead of
    // first stopping near the ship and translating there at low altitude.
    LOCAL RB_SPEED_PROFILE IS MIN(RETURN_MAX_HORIZONTAL_SPEED,
        RB_H_POS:MAG / MAX(RB_TGO, 1)).
    LOCAL RB_DESIRED_H_VEL IS RB_DIRECTION * RB_SPEED_PROFILE.
    LOCAL RB_H_ACCEL IS CLAMPV((RB_DESIRED_H_VEL - RB_H_VEL) * 0.35,
        RETURN_MAX_HORIZONTAL_ACCEL).
    // Keep the entire burn on the horizontal half-plane opposite the velocity
    // measured at ignition. Guidance may reduce that component to zero, but it
    // cannot swing the nozzle back and start a second, opposite correction.
    LOCAL RB_BRAKING_ACCEL IS VDOT(RB_H_ACCEL, RB_BRAKE_DIRECTION).
    IF RB_BRAKING_ACCEL < 0 {
        SET RB_H_ACCEL TO RB_H_ACCEL
            - RB_BRAKE_DIRECTION * RB_BRAKING_ACCEL.
    }
    SET RB_FILTERED_H_ACCEL TO RB_FILTERED_H_ACCEL * 0.92
        + RB_H_ACCEL * 0.08.
    LOCAL RB_VERTICAL_THRUST IS RB_G * 0.55.
    LOCAL RB_MAX_H_ACCEL IS RB_VERTICAL_THRUST * TAN(RETURN_BURN_MAX_TILT).
    SET RB_FILTERED_H_ACCEL TO CLAMPV(RB_FILTERED_H_ACCEL, RB_MAX_H_ACCEL).
    LOCAL RB_THRUST IS RB_UP * RB_VERTICAL_THRUST + RB_FILTERED_H_ACCEL.
    LOCAL RB_THROTTLE IS CLAMP(SHIP:MASS * RB_THRUST:MAG /
        MAX(SHIP:AVAILABLETHRUST, 0.001), 0, 1).

    LOCK STEERING TO LOOKDIRUP(RB_THRUST, SHIP:FACING:TOPVECTOR).
    LOCK THROTTLE TO RB_THROTTLE.
    LOCAL RB_PREDICTED_MISS IS RB_H_POS - RB_H_VEL * RB_TGO.
    SET RETURN_BURN_DONE TO (TIME:SECONDS - RETURN_BURN_START >= 3
        AND RB_PREDICTED_MISS:MAG <= RETURN_BURN_END_ERROR)
        OR TIME:SECONDS - RETURN_BURN_START >= RETURN_BURN_MAX_TIME.

    IF TIME:SECONDS - LAST_LOG >= TELEMETRY_PERIOD {
        WRITE_TELEMETRY("BOOSTBACK", MISSION_ID, SHIP:ALTITUDE, 0,
            VDOT(RB_REL_VEL, RB_UP), RB_H_VEL:MAG, RB_H_POS:MAG,
            RB_THROTTLE, VANG(RB_THRUST, RB_UP)).
        SET LAST_LOG TO TIME:SECONDS.
    }
    WAIT 0.02.
}

// 3) Leave time between boost-back and entry braking for one bounded attitude
// transition.  Hold its final direction instead of chasing a rapidly changing
// velocity suffix through the atmosphere.
LOCK THROTTLE TO 0.
PRINT "SMOOTH ENTRY ATTITUDE SLEW" AT(0,11).
LOCAL ENTRY_SLEW_START IS TIME:SECONDS.
LOCAL ENTRY_SLEW_VECTOR IS SHIP:FACING:FOREVECTOR:NORMALIZED.
UNTIL TIME:SECONDS - ENTRY_SLEW_START >= ENTRY_ATTITUDE_SLEW_SECONDS {
    LOCAL ENTRY_SLEW_RAW IS CLAMP((TIME:SECONDS - ENTRY_SLEW_START)
        / ENTRY_ATTITUDE_SLEW_SECONDS, 0, 1).
    LOCAL ENTRY_SLEW_BLEND IS ENTRY_SLEW_RAW^2
        * (3 - 2 * ENTRY_SLEW_RAW).
    LOCAL ENTRY_UP_TARGET IS SHIP:UP:VECTOR:NORMALIZED.
    LOCAL ENTRY_SLEW_COMMAND IS (ENTRY_SLEW_VECTOR
        * (1 - ENTRY_SLEW_BLEND) + ENTRY_UP_TARGET
        * ENTRY_SLEW_BLEND):NORMALIZED.
    LOCK STEERING TO LOOKDIRUP(ENTRY_SLEW_COMMAND,
        SHIP:FACING:TOPVECTOR).
    WAIT 0.05.
}
LOCK STEERING TO UP.
PRINT "VERTICAL AERODYNAMIC COAST" AT(0,11).
// Do not sample the speed condition only once at the altitude boundary. Wait
// until both are true so this single entry burn cannot be accidentally skipped.
WAIT UNTIL SHIP:ALTITUDE <= ENTRY_BURN_ALTITUDE
    AND SHIP:VERTICALSPEED < ENTRY_TARGET_VERTICAL_SPEED.
LOCAL ENTRY_BURN_START IS TIME:SECONDS.
PRINT "SINGLE ENTRY BRAKING BURN" AT(0,11).
// Hold the completed vertical attitude for the entire burn; no velocity-vector
// tracking or reverse correction is allowed here.
LOCK STEERING TO UP.
UNTIL SHIP:VERTICALSPEED >= ENTRY_TARGET_VERTICAL_SPEED
      OR TIME:SECONDS - ENTRY_BURN_START >= ENTRY_BURN_MAX_TIME {
    LOCAL ENTRY_UP IS SHIP:UP:VECTOR:NORMALIZED.
    LOCAL ENTRY_REL_POS IS NET_POSITION(RECOVERY_SHIP) - SHIP:POSITION.
    LOCAL ENTRY_H_POS IS VXCL(ENTRY_UP, ENTRY_REL_POS).
    LOCAL ENTRY_REL_VEL IS SHIP:VELOCITY:SURFACE
        - RECOVERY_SHIP:VELOCITY:SURFACE.
    LOCAL ENTRY_H_VEL IS VXCL(ENTRY_UP, ENTRY_REL_VEL).
    LOCAL ENTRY_VERTICAL_V IS VDOT(ENTRY_REL_VEL, ENTRY_UP).
    LOCAL ENTRY_RAMP IS CLAMP((TIME:SECONDS - ENTRY_BURN_START)
        / ENTRY_THROTTLE_RAMP_SECONDS, 0, 1).
    LOCK THROTTLE TO ENTRY_BURN_THROTTLE * ENTRY_RAMP.

    IF TIME:SECONDS - LAST_LOG >= TELEMETRY_PERIOD {
        WRITE_TELEMETRY("ENTRY", MISSION_ID, SHIP:ALTITUDE, 0,
            VDOT(ENTRY_REL_VEL, ENTRY_UP), ENTRY_H_VEL:MAG,
            ENTRY_H_POS:MAG, ENTRY_BURN_THROTTLE * ENTRY_RAMP,
            VANG(SHIP:FACING:FOREVECTOR, ENTRY_UP)).
        SET LAST_LOG TO TIME:SECONDS.
    }
    WAIT 0.02.
}
LOCK THROTTLE TO 0.
LOCK STEERING TO UP.
PRINT "ATMOSPHERIC DECELERATION" AT(0,11).
WAIT UNTIL SHIP:ALTITUDE <= TERMINAL_START_ALTITUDE.

// 4) G-FOLD-inspired constrained powered descent.  Solve one arrival time from
// the measured entry state and fly that fixed cubic trajectory.  Only inside
// PID_SWITCH_HEIGHT do we hand over to local position/velocity feedback.  This
// avoids the old receding-horizon hover-and-translate behaviour.
PRINT "FIXED-TRAJECTORY POWERED DESCENT" AT(0,11).
LOCAL VERTICAL_INTEGRAL IS 0.
LOCAL PREVIOUS_TIME IS TIME:SECONDS.
LOCAL PLAN_UP IS SHIP:UP:VECTOR:NORMALIZED.
LOCAL PLAN_REL_POS IS NET_POSITION(RECOVERY_SHIP) - SHIP:POSITION.
LOCAL PLAN_HOOK_HEIGHT IS -VDOT(PLAN_REL_POS, PLAN_UP) + HOOK_ABOVE_COM.
LOCAL PLAN_H_POS IS VXCL(PLAN_UP, PLAN_REL_POS).
LOCAL PLAN_REL_VEL IS SHIP:VELOCITY:SURFACE
    - RECOVERY_SHIP:VELOCITY:SURFACE.
LOCAL PLAN_VERTICAL_V IS VDOT(PLAN_REL_VEL, PLAN_UP).
LOCAL PLAN_H_VEL IS VXCL(PLAN_UP, PLAN_REL_VEL).
LOCAL PLAN_VERTICAL_TGO IS 2 * MAX(PLAN_HOOK_HEIGHT, 1)
    / MAX(-PLAN_VERTICAL_V + CAPTURE_FINAL_SPEED, 1).
LOCAL PLAN_HORIZONTAL_TGO IS 2 * PLAN_H_POS:MAG
    / MAX(PLAN_H_VEL:MAG + TERMINAL_HORIZONTAL_SPEED, 10).
LOCAL PLAN_TGO IS CLAMP(MAX(PLAN_VERTICAL_TGO, PLAN_HORIZONTAL_TGO),
    TERMINAL_TGO_MIN, TERMINAL_TGO_MAX).
LOCAL PLAN_ARRIVAL_TIME IS TIME:SECONDS + PLAN_TGO.
LOCAL WAS_PID_MODE IS FALSE.
LOCAL FILTERED_H_ACCEL IS V(0,0,0).
SET LAST_LOG TO TIME:SECONDS.

UNTIL HOOK_CAPTURED() {
    LOCAL NOW IS TIME:SECONDS.
    LOCAL DT IS CLAMP(NOW - PREVIOUS_TIME, 0.001, 0.1).
    SET PREVIOUS_TIME TO NOW.

    LOCAL UP_VEC IS SHIP:UP:VECTOR:NORMALIZED.
    LOCAL REL_POS IS NET_POSITION(RECOVERY_SHIP) - SHIP:POSITION.
    LOCAL HEIGHT IS -VDOT(REL_POS, UP_VEC).
    LOCAL HOOK_HEIGHT IS HEIGHT + HOOK_ABOVE_COM.
    LOCAL HORIZONTAL_POS IS VXCL(UP_VEC, REL_POS).
    LOCAL REL_VEL IS SHIP:VELOCITY:SURFACE - RECOVERY_SHIP:VELOCITY:SURFACE.
    LOCAL VERTICAL_V IS VDOT(REL_VEL, UP_VEC).
    LOCAL HORIZONTAL_VEL IS VXCL(UP_VEC, REL_VEL).
    LOCAL G_ACC IS SHIP:BODY:MU / ((SHIP:BODY:RADIUS + SHIP:ALTITUDE)^2).
    LOCAL AVAILABLE_ACC IS SHIP:AVAILABLETHRUST / MAX(SHIP:MASS, 0.001).

    LOCAL PID_MODE IS HOOK_HEIGHT <= PID_SWITCH_HEIGHT.
    IF PID_MODE AND NOT WAS_PID_MODE {
        SET VERTICAL_INTEGRAL TO 0.
        PRINT "NEAR-FIELD PID HANDOVER" AT(0,11).
    }
    SET WAS_PID_MODE TO PID_MODE.

    LOCAL CENTERING_REQUIRED IS PID_MODE
        AND HOOK_HEIGHT < CENTERING_HOLD_ALTITUDE
        AND HORIZONTAL_POS:MAG > CENTERING_HOLD_ERROR.
    LOCAL WIRE_REQUIRED IS HOOK_HEIGHT < WIRE_HOLD_HEIGHT
        AND NOT NET_CLOSED(RECOVERY_SHIP).

    LOCAL TGO IS MAX(PLAN_ARRIVAL_TIME - NOW, 1.5).
    LOCAL TARGET_VERTICAL_V IS -CAPTURE_FINAL_SPEED.
    LOCAL NET_VERTICAL_ACCEL IS -6 * MAX(HOOK_HEIGHT, 0) / (TGO^2)
        - (4 * VERTICAL_V + 2 * TARGET_VERTICAL_V) / TGO.
    IF VERTICAL_V < 0 {
        LOCAL SAFE_BRAKING_ACCEL IS (VERTICAL_V^2)
            / (2 * MAX(HOOK_HEIGHT, 1)) * STOP_DISTANCE_SAFETY.
        SET NET_VERTICAL_ACCEL TO MAX(NET_VERTICAL_ACCEL,
            SAFE_BRAKING_ACCEL).
    }
    LOCAL VERTICAL_THRUST_CMD IS G_ACC + NET_VERTICAL_ACCEL.
    LOCAL H_ACCEL IS 6 * HORIZONTAL_POS / (TGO^2)
        - 4 * HORIZONTAL_VEL / TGO.
    SET H_ACCEL TO CLAMPV(H_ACCEL, TERMINAL_MAX_HORIZONTAL_ACCEL).

    IF PID_MODE {
        // Use the altitude available above the frame: translate promptly after
        // handover, then taper below the 4 m/s capture envelope near the net.
        LOCAL PID_H_SPEED IS MAX(TERMINAL_HORIZONTAL_SPEED,
            MIN(10, MAX(HOOK_HEIGHT, 0) * 0.03)).
        LOCAL DESIRED_H_VEL IS CLAMPV(HORIZONTAL_POS * H_POS_KP_LOW,
            PID_H_SPEED).
        SET H_ACCEL TO CLAMPV((DESIRED_H_VEL - HORIZONTAL_VEL) * H_VEL_KP,
            TERMINAL_MAX_HORIZONTAL_ACCEL).

        LOCAL PID_TARGET_V IS -MAX(CAPTURE_FINAL_SPEED,
            MIN(8, MAX(HOOK_HEIGHT, 0) * 0.04)).
        // Only a badly missed frame mouth slows to a crawl; it never commands
        // an extended zero-speed hover. Cable closure itself still gets a short
        // stationary window so the stage cannot cross open lines.
        IF CENTERING_REQUIRED { SET PID_TARGET_V TO -CAPTURE_FINAL_SPEED. }
        IF WIRE_REQUIRED { SET PID_TARGET_V TO 0. }
        SET VERTICAL_INTEGRAL TO CLAMP(VERTICAL_INTEGRAL
            + (PID_TARGET_V - VERTICAL_V) * DT, -10, 10).
        SET VERTICAL_THRUST_CMD TO G_ACC
            + V_VEL_KP * (PID_TARGET_V - VERTICAL_V)
            + V_VEL_KI * VERTICAL_INTEGRAL.
    }
    SET FILTERED_H_ACCEL TO FILTERED_H_ACCEL * (1 - TERMINAL_ACCEL_FILTER)
        + H_ACCEL * TERMINAL_ACCEL_FILTER.
    SET H_ACCEL TO FILTERED_H_ACCEL.
    SET VERTICAL_THRUST_CMD TO CLAMP(VERTICAL_THRUST_CMD, 0,
        AVAILABLE_ACC * 0.96).

    LOCAL ALT_BLEND IS CLAMP(HOOK_HEIGHT / 800, 0, 1).
    LOCAL TILT_LIMIT IS ENTRY_MAX_TILT * ALT_BLEND
        + LANDING_MAX_TILT * (1 - ALT_BLEND).
    LOCAL MAX_H_ACCEL IS MAX(VERTICAL_THRUST_CMD, G_ACC * 0.2)
        * TAN(TILT_LIMIT).
    SET H_ACCEL TO CLAMPV(H_ACCEL, MAX_H_ACCEL).
    LOCAL DESIRED_THRUST IS UP_VEC * MAX(VERTICAL_THRUST_CMD, G_ACC * 0.2)
        + H_ACCEL.
    LOCAL TILT_CMD IS VANG(DESIRED_THRUST, UP_VEC).
    LOCAL THROTTLE_CMD IS CLAMP(SHIP:MASS * DESIRED_THRUST:MAG /
        MAX(SHIP:AVAILABLETHRUST, 0.001), 0, 1).
    LOCK STEERING TO LOOKDIRUP(DESIRED_THRUST, SHIP:FACING:TOPVECTOR).
    LOCK THROTTLE TO THROTTLE_CMD.

    LOCAL GUIDANCE_PHASE IS "TRAJECTORY".
    IF PID_MODE { SET GUIDANCE_PHASE TO "PID_TERMINAL". }
    IF NOW - LAST_LOG >= TELEMETRY_PERIOD {
        WRITE_TELEMETRY(GUIDANCE_PHASE, MISSION_ID, SHIP:ALTITUDE, HOOK_HEIGHT,
            VERTICAL_V, HORIZONTAL_VEL:MAG, HORIZONTAL_POS:MAG,
            THROTTLE_CMD, TILT_CMD).
        SET LAST_LOG TO NOW.
    }
    PRINT "phase       " + GUIDANCE_PHASE + " / "
        + NET_STATE(RECOVERY_SHIP) + "       " AT(0,12).
    PRINT "hook height " + ROUND(HOOK_HEIGHT,1) + " m    " AT(0,13).
    PRINT "vertical    " + ROUND(VERTICAL_V,2) + " m/s  " AT(0,14).
    PRINT "cross error " + ROUND(HORIZONTAL_POS:MAG,1) + " m    " AT(0,15).
    PRINT "throttle    " + ROUND(THROTTLE_CMD,3) + "      " AT(0,16).

    IF AG10 {
        PRINT "MANUAL ABORT (AG10)".
        BREAK.
    }
    WAIT 0.02.
}

LOCK THROTTLE TO 0.
LOCK STEERING TO UP.
RCS OFF.
PRINT "CAPTURE COMPLETE" AT(0,18).
LOG MISSION_ID + ",CAPTURE," + ROUND(TIME:SECONDS,3) TO "0:/cz10b/telemetry.csv".
WAIT UNTIL FALSE.
