@LAZYGLOBAL OFF.

// Autonomous upper-stage insertion.  The first burn establishes the 100 km
// apoapsis; a short prograde burn around apoapsis then raises periapsis above
// the atmosphere without interfering with the booster's recovery computer.
LOCAL TARGET_APOAPSIS IS 100000.
LOCAL TARGET_PERIAPSIS IS 90000.
LOCAL SAFE_APOAPSIS IS 120000.

SAS OFF.
RCS ON.
LOCK THROTTLE TO 0.
LOCAL ENGINE_LOAD_DEADLINE IS TIME:SECONDS + 10.
WAIT UNTIL SHIP:ENGINES:LENGTH > 0
    OR TIME:SECONDS >= ENGINE_LOAD_DEADLINE.
LOCAL UPPER_ENGINES IS SHIP:ENGINES.
IF UPPER_ENGINES:LENGTH = 0 {
    PRINT "UPPER STAGE ABORT: engine unavailable".
    SHUTDOWN.
}
LOCK STEERING TO PROGRADE.

// Do not leave an activated zero-throttle engine running through the long
// coast.  Besides wasting the engage state, legacy ModuleEngines audio remains
// audible while active.  Activate once per real burn and shut down at cutoff.
IF SHIP:APOAPSIS < TARGET_APOAPSIS {
    FOR ENGINE IN UPPER_ENGINES {
        SET ENGINE:THRUSTLIMIT TO 100.
        ENGINE:ACTIVATE.
    }
    LOCK THROTTLE TO 1.
    LOCAL FIRST_IGNITION_DEADLINE IS TIME:SECONDS + 3.
    WAIT UNTIL SHIP:AVAILABLETHRUST > 1
        OR TIME:SECONDS >= FIRST_IGNITION_DEADLINE.
    IF SHIP:AVAILABLETHRUST <= 1 {
        // A single delayed retry closes the unpack race without replaying the
        // engine engage event every physics frame.
        FOR ENGINE IN UPPER_ENGINES { ENGINE:ACTIVATE. }
        SET FIRST_IGNITION_DEADLINE TO TIME:SECONDS + 3.
        WAIT UNTIL SHIP:AVAILABLETHRUST > 1
            OR TIME:SECONDS >= FIRST_IGNITION_DEADLINE.
    }
    IF SHIP:AVAILABLETHRUST <= 1 {
        PRINT "UPPER STAGE ABORT: first ignition failed".
        LOCK THROTTLE TO 0.
        FOR ENGINE IN UPPER_ENGINES { ENGINE:SHUTDOWN. }
        SHUTDOWN.
    }
    WAIT UNTIL SHIP:APOAPSIS >= TARGET_APOAPSIS.
    LOCK THROTTLE TO 0.
    FOR ENGINE IN UPPER_ENGINES { ENGINE:SHUTDOWN. }
}

// The enlarged payload needs a finite burn centred on apoapsis.  Begin early
// and use full thrust; the former 10--20% burn started too late, continued far
// down the descending branch and raised apoapsis much more than periapsis.
WAIT UNTIL ETA:APOAPSIS <= 20 OR SHIP:VERTICALSPEED < 0.
SAS OFF.
LOCK STEERING TO PROGRADE.
FOR ENGINE IN UPPER_ENGINES { ENGINE:ACTIVATE. }
LOCK THROTTLE TO 1.
LOCAL CIRCULARIZATION_IGNITION_DEADLINE IS TIME:SECONDS + 3.
WAIT UNTIL SHIP:AVAILABLETHRUST > 1
    OR TIME:SECONDS >= CIRCULARIZATION_IGNITION_DEADLINE.
IF SHIP:AVAILABLETHRUST <= 1 {
    FOR ENGINE IN UPPER_ENGINES { ENGINE:ACTIVATE. }
    SET CIRCULARIZATION_IGNITION_DEADLINE TO TIME:SECONDS + 3.
    WAIT UNTIL SHIP:AVAILABLETHRUST > 1
        OR TIME:SECONDS >= CIRCULARIZATION_IGNITION_DEADLINE.
}
IF SHIP:AVAILABLETHRUST <= 1 {
    PRINT "UPPER STAGE ABORT: circularization ignition failed".
    LOCK THROTTLE TO 0.
    FOR ENGINE IN UPPER_ENGINES { ENGINE:SHUTDOWN. }
    SHUTDOWN.
}
UNTIL SHIP:PERIAPSIS >= TARGET_PERIAPSIS
      OR (SHIP:PERIAPSIS >= 72000
          AND SHIP:APOAPSIS >= SAFE_APOAPSIS) {
    WAIT 0.02.
}
LOCK THROTTLE TO 0.
FOR ENGINE IN UPPER_ENGINES { ENGINE:SHUTDOWN. }
PRINT "UPPER STAGE ORBIT ACHIEVED".
PRINT "AP " + ROUND(SHIP:APOAPSIS / 1000,1) + " km".
PRINT "PE " + ROUND(SHIP:PERIAPSIS / 1000,1) + " km".
