@LAZYGLOBAL OFF.

// Autonomous upper-stage insertion.  The first prograde burn preserves the
// separation attitude and establishes the 100 km apoapsis.  The insertion burn
// then regulates radial motion while spending the remaining thrust horizontally;
// this prevents a long finite burn from driving apoapsis through the 110 km
// ceiling before periapsis reaches the accepted orbit.
LOCAL TARGET_APOAPSIS IS 100000.
LOCAL TARGET_PERIAPSIS IS 90000.
LOCAL MAX_APOAPSIS IS 110000.
LOCAL MAX_PERIAPSIS IS 105000.
LOCAL UPPER_THRUST_LIMIT IS 25.
LOCAL INSERTION_TARGET_ALTITUDE IS 100000.
LOCAL INSERTION_RADIAL_POSITION_GAIN IS 0.00010.
LOCAL INSERTION_RADIAL_VELOCITY_GAIN IS 0.040.
LOCAL INSERTION_MAX_RADIAL_FRACTION IS 0.80.

SAS OFF.
RCS ON.
// Bind fly-by-wire once.  Updating command variables avoids a kOS debug log
// allocation on every circularization physics frame.
LOCAL UPPER_THROTTLE_CMD IS 0.
LOCAL UPPER_STEERING_CMD IS PROGRADE.
LOCK THROTTLE TO UPPER_THROTTLE_CMD.
LOCAL ENGINE_LOAD_DEADLINE IS TIME:SECONDS + 10.
WAIT UNTIL SHIP:ENGINES:LENGTH > 0
    OR TIME:SECONDS >= ENGINE_LOAD_DEADLINE.
LOCAL UPPER_ENGINES IS SHIP:ENGINES.
IF UPPER_ENGINES:LENGTH = 0 {
    PRINT "UPPER STAGE ABORT: engine unavailable".
    SHUTDOWN.
}
LOCK STEERING TO UPPER_STEERING_CMD.

// Do not leave an activated zero-throttle engine running through the long
// coast.  Besides wasting the engage state, legacy ModuleEngines audio remains
// audible while active.  Activate once per real burn and shut down at cutoff.
IF SHIP:APOAPSIS < TARGET_APOAPSIS {
    FOR ENGINE IN UPPER_ENGINES {
        // A longer first burn increases the physical separation at first
        // cutoff while remaining well above the required 10% setting.
        SET ENGINE:THRUSTLIMIT TO UPPER_THRUST_LIMIT.
        ENGINE:ACTIVATE.
    }
    SET UPPER_THROTTLE_CMD TO 1.
    LOCAL FIRST_IGNITION_DEADLINE IS TIME:SECONDS + 3.
    WAIT UNTIL SHIP:AVAILABLETHRUST > 1
        OR TIME:SECONDS >= FIRST_IGNITION_DEADLINE.
    IF SHIP:AVAILABLETHRUST <= 1 {
        // A single delayed retry closes the unpack race without replaying the
        // engine engage event every physics frame.
        FOR ENGINE IN UPPER_ENGINES { ENGINE:ACTIVATE. }
        SET FIRST_IGNITION_DEADLINE TO TIME:SECONDS + 3.
        WAIT UNTIL SHIP:AVAILABLETHRUST > 1
            OR TIME:SECONDS >= FIRST_IGNITION_DEADLINE.
    }
    IF SHIP:AVAILABLETHRUST <= 1 {
        PRINT "UPPER STAGE ABORT: first ignition failed".
        SET UPPER_THROTTLE_CMD TO 0.
        FOR ENGINE IN UPPER_ENGINES { ENGINE:SHUTDOWN. }
        SHUTDOWN.
    }
    WAIT UNTIL SHIP:APOAPSIS >= TARGET_APOAPSIS.
    SET UPPER_THROTTLE_CMD TO 0.
    FOR ENGINE IN UPPER_ENGINES { ENGINE:SHUTDOWN. }
}

// Make the first cutoff physically observable by both KSP and the acceptance
// recorder.  At this point real separation distance is already well beyond the
// required 10 km; a one-second coast does not materially change insertion.
WAIT 1.
SAS OFF.
FOR ENGINE IN UPPER_ENGINES {
    SET ENGINE:THRUSTLIMIT TO UPPER_THRUST_LIMIT.
    ENGINE:ACTIVATE.
}
SET UPPER_THROTTLE_CMD TO 1.
LOCAL CIRCULARIZATION_IGNITION_DEADLINE IS TIME:SECONDS + 3.
WAIT UNTIL SHIP:AVAILABLETHRUST > 1
    OR TIME:SECONDS >= CIRCULARIZATION_IGNITION_DEADLINE.
IF SHIP:AVAILABLETHRUST <= 1 {
    FOR ENGINE IN UPPER_ENGINES { ENGINE:ACTIVATE. }
    SET CIRCULARIZATION_IGNITION_DEADLINE TO TIME:SECONDS + 3.
    WAIT UNTIL SHIP:AVAILABLETHRUST > 1
        OR TIME:SECONDS >= CIRCULARIZATION_IGNITION_DEADLINE.
}
IF SHIP:AVAILABLETHRUST <= 1 {
    PRINT "UPPER STAGE ABORT: circularization ignition failed".
    SET UPPER_THROTTLE_CMD TO 0.
    FOR ENGINE IN UPPER_ENGINES { ENGINE:SHUTDOWN. }
    SHUTDOWN.
}
UNTIL (SHIP:APOAPSIS >= 95000 AND SHIP:APOAPSIS <= MAX_APOAPSIS
        AND SHIP:PERIAPSIS >= TARGET_PERIAPSIS
        AND SHIP:PERIAPSIS <= MAX_PERIAPSIS)
      OR SHIP:APOAPSIS > MAX_APOAPSIS
      OR SHIP:PERIAPSIS > MAX_PERIAPSIS {
    LOCAL UPPER_UP IS SHIP:UP:VECTOR:NORMALIZED.
    LOCAL UPPER_ORBIT_VELOCITY IS SHIP:VELOCITY:ORBIT.
    LOCAL UPPER_RADIAL_VELOCITY IS VDOT(UPPER_ORBIT_VELOCITY, UPPER_UP).
    LOCAL UPPER_HORIZONTAL_VELOCITY IS VXCL(UPPER_UP, UPPER_ORBIT_VELOCITY).
    LOCAL UPPER_HORIZONTAL_DIRECTION IS SHIP:FACING:VECTOR.
    IF UPPER_HORIZONTAL_VELOCITY:MAG > 0.1 {
        SET UPPER_HORIZONTAL_DIRECTION TO
            UPPER_HORIZONTAL_VELOCITY:NORMALIZED.
    }
    LOCAL UPPER_RADIUS IS SHIP:BODY:RADIUS + SHIP:ALTITUDE.
    LOCAL UPPER_GRAVITY IS SHIP:BODY:MU / (UPPER_RADIUS^2).
    LOCAL UPPER_CENTRIFUGAL IS UPPER_HORIZONTAL_VELOCITY:MAG^2
        / UPPER_RADIUS.
    LOCAL UPPER_AVAILABLE_ACCEL IS SHIP:AVAILABLETHRUST
        / MAX(SHIP:MASS, 0.001).
    LOCAL UPPER_RADIAL_THRUST IS UPPER_GRAVITY - UPPER_CENTRIFUGAL
        + (INSERTION_TARGET_ALTITUDE - SHIP:ALTITUDE)
            * INSERTION_RADIAL_POSITION_GAIN
        - UPPER_RADIAL_VELOCITY * INSERTION_RADIAL_VELOCITY_GAIN.
    SET UPPER_RADIAL_THRUST TO MAX(
        -UPPER_AVAILABLE_ACCEL * INSERTION_MAX_RADIAL_FRACTION,
        MIN(UPPER_AVAILABLE_ACCEL * INSERTION_MAX_RADIAL_FRACTION,
            UPPER_RADIAL_THRUST)).
    LOCAL UPPER_HORIZONTAL_THRUST IS SQRT(MAX(UPPER_AVAILABLE_ACCEL^2
        - UPPER_RADIAL_THRUST^2, 0.01)).
    LOCAL UPPER_THRUST_VECTOR IS UPPER_HORIZONTAL_DIRECTION
            * UPPER_HORIZONTAL_THRUST
        + UPPER_UP * UPPER_RADIAL_THRUST.
    SET UPPER_STEERING_CMD TO LOOKDIRUP(UPPER_THRUST_VECTOR, UPPER_UP).
    WAIT 0.02.
}
SET UPPER_THROTTLE_CMD TO 0.
FOR ENGINE IN UPPER_ENGINES { ENGINE:SHUTDOWN. }
IF SHIP:APOAPSIS >= 95000 AND SHIP:APOAPSIS <= MAX_APOAPSIS
    AND SHIP:PERIAPSIS >= TARGET_PERIAPSIS
    AND SHIP:PERIAPSIS <= MAX_PERIAPSIS {
    PRINT "UPPER STAGE ORBIT ACHIEVED".
} ELSE {
    PRINT "UPPER STAGE ORBIT OUTSIDE ACCEPTANCE".
}
PRINT "AP " + ROUND(SHIP:APOAPSIS / 1000,1) + " km".
PRINT "PE " + ROUND(SHIP:PERIAPSIS / 1000,1) + " km".
